
        document.addEventListener('DOMContentLoaded', function() {
            const glossaryData = [
                // A
                { term: "Agile", definition: "A project management methodology focused on iterative development, delivering work in small continuous cycles, and rapid adaptation to change." },
                { term: "API", definition: "Application Programming Interface. A set of defined protocols and tools for building software applications that specify how software components should interact." },
                { term: "Automation", definition: "The use of technology to perform repetitive tasks with minimal human intervention, improving speed, efficiency, and reducing errors." },
                { term: "ARM (Architecture)", definition: "Advanced RISC Machine. A processor architecture design philosophy emphasizing reduced instruction sets, widely used in mobile devices and IoT." },
                { term: "ACL", definition: "Access Control List. A security mechanism defining which users or systems have permission to access specific resources or perform certain operations." },
                { term: "ARP", definition: "Address Resolution Protocol. A network protocol that maps IP addresses to physical MAC addresses on a local network." },
                
                // B
                { term: "Blockchain", definition: "A decentralized, distributed digital ledger recording transactions across many computers, ensuring data integrity and resistance to tampering." },
                { term: "Bandwidth", definition: "The maximum data transfer rate of a network or internet connection, measured in bits per second (bps), determining how much data can be sent at once." },
                { term: "Backend", definition: "The server-side of a website or application, responsible for storing and organizing data, and ensuring client-side functionality works correctly." },
                { term: "Bytecode", definition: "Intermediate code generated by compilers that is not specific to any hardware platform, executed by a virtual machine like the Java Virtual Machine." },
                { term: "BGP", definition: "Border Gateway Protocol. The primary routing protocol used to exchange routing information between autonomous systems on the internet." },
                { term: "BIOS", definition: "Basic Input/Output System. Firmware that initializes hardware during the boot process before the operating system loads." },
                
                // C
                { term: "Cloud Computing", definition: "The delivery of computing services—servers, storage, databases, networking, software, analytics—over the internet." },
                { term: "CI/CD", definition: "Continuous Integration/Continuous Delivery. A DevOps practice automating the merging of code changes and delivery of new code to users." },
                { term: "CRM", definition: "Customer Relationship Management. Software managing company interactions with current and potential customers, focusing on customer data analysis." },
                { term: "Containerization", definition: "A lightweight virtualization technology packaging applications and their dependencies into isolated containers for consistent deployment across environments." },
                { term: "CDN", definition: "Content Delivery Network. A distributed network of servers delivering web content to users from geographically closer locations for improved performance." },
                { term: "CORS", definition: "Cross-Origin Resource Sharing. A mechanism allowing web servers to permit restricted resources to be accessed from origins other than the originating domain." },
                { term: "Caching", definition: "Storing frequently accessed data in faster, temporary storage to reduce retrieval time and improve system performance." },
                { term: "Cryptography", definition: "The science of encoding information to prevent unauthorized access, using mathematical algorithms and keys to secure data." },
                
                // D
                { term: "DevOps", definition: "A set of practices combining software development (Dev) and IT operations (Ops) to shorten the development lifecycle and provide continuous delivery." },
                { term: "Data Center", definition: "A dedicated physical facility housing critical computer systems and associated components like telecommunications and storage systems." },
                { term: "DDoS Attack", definition: "Distributed Denial of Service Attack. An attempt to disrupt normal traffic by overwhelming a server, service or network with internet traffic." },
                { term: "DNS", definition: "Domain Name System. A protocol converting human-readable domain names into IP addresses that computers use to locate resources on the internet." },
                { term: "Docker", definition: "A containerization platform enabling developers to package applications into standardized units called containers for easy deployment and scaling." },
                { term: "DHCP", definition: "Dynamic Host Configuration Protocol. A network protocol automatically assigning IP addresses and other network configuration parameters to devices." },
                { term: "DMS", definition: "Data Management System. Software managing the storage, retrieval, and manipulation of data within an organization." },
                
                // E
                { term: "E-commerce", definition: "Electronic commerce. The buying and selling of goods or services using the internet with transfer of money and data to execute transactions." },
                { term: "Encryption", definition: "The process of encoding information so only authorized parties can access it, typically using a secret key." },
                { term: "ERP", definition: "Enterprise Resource Planning. Software managing day-to-day business activities such as accounting, procurement, project management, and manufacturing." },
                { term: "Edge Computing", definition: "Computing performed at the edge of networks closer to data sources, reducing latency and enabling faster processing of real-time data." },
                { term: "ETL", definition: "Extract, Transform, Load. A process extracting data from sources, transforming it into a suitable format, and loading it into a target system." },
                
                // F
                { term: "Firewall", definition: "A network security device monitoring and filtering incoming and outgoing traffic based on established security policies." },
                { term: "Frontend", definition: "The user-facing side of a website or application built with HTML, CSS, and JavaScript, encompassing what users see and interact with." },
                { term: "Framework", definition: "A reusable set of libraries and tools providing a foundation for building applications, reducing development time and effort." },
                { term: "FTP", definition: "File Transfer Protocol. A standard network protocol used to transfer files between computers over the internet." },
                
                // G
                { term: "Garbage Collection", definition: "An automatic memory management process removing unused objects from memory to prevent memory leaks and optimize performance." },
                { term: "Gateway", definition: "A network component that serves as an access point to another network or system, often translating between different protocols." },
                { term: "GPU", definition: "Graphics Processing Unit. A specialized processor designed for parallel processing, commonly used for graphics rendering and machine learning tasks." },
                { term: "GraphQL", definition: "A query language and runtime for APIs allowing clients to request exactly the data they need, providing more efficient alternatives to REST." },
                
                // H
                { term: "Hosting", definition: "The service of running and maintaining computer systems that store websites and make them accessible on the World Wide Web." },
                { term: "HTTPS", definition: "HyperText Transfer Protocol Secure. A secure version of HTTP encrypting data transmission between clients and servers using SSL/TLS." },
                { term: "Hash Function", definition: "A mathematical algorithm converting input data into a fixed-size string of characters, used for security, checksums, and data integrity verification." },
                { term: "Hypervisor", definition: "Software or firmware enabling multiple operating systems to run simultaneously on a single physical machine through virtualization." },
                
                // I
                { term: "IT Infrastructure", definition: "The foundational components—hardware, software, networks, facilities—supporting a business's IT and overall operations." },
                { term: "IoT", definition: "Internet of Things. The network of physical devices embedded with sensors and connectivity enabling data collection and exchange over the internet." },
                { term: "IaaS", definition: "Infrastructure as a Service. A cloud computing model providing virtualized computing resources over the internet on a pay-as-you-go basis." },
                { term: "IP Address", definition: "Internet Protocol Address. A unique numerical identifier assigned to each device connected to a computer network using the Internet Protocol." },
                { term: "ISP", definition: "Internet Service Provider. A company providing individuals and organizations with internet connectivity and related services." },
                
                // J
                { term: "JSON", definition: "JavaScript Object Notation. A lightweight, text-based data format widely used for data interchange between web servers and clients." },
                { term: "JWT", definition: "JSON Web Token. A compact token format for securely transmitting information between parties as a JSON object, commonly used for authentication." },
                
                // K
                { term: "Kubernetes", definition: "An open-source container orchestration platform automating the deployment, scaling, and management of containerized applications." },
                
                // L
                { term: "Latency", definition: "The delay before data transfer begins following a transfer instruction, measured in milliseconds and impacting application responsiveness." },
                { term: "Load Balancer", definition: "A device or software distributing network traffic across multiple servers to optimize resource utilization and prevent server overload." },
                { term: "Logging", definition: "The process of recording system events, errors, and activities to files for monitoring, debugging, and compliance purposes." },
                
                // M
                { term: "Mobile Application", definition: "Software designed to run on smartphones, tablets, and other mobile devices, built for operating systems like iOS or Android." },
                { term: "Microservices", definition: "An architectural approach structuring an application as loosely coupled, independently deployable small services communicating via APIs." },
                { term: "Machine Learning", definition: "A subset of artificial intelligence where algorithms learn patterns from data to make predictions or decisions without explicit programming." },
                { term: "Middleware", definition: "Software acting as an intermediary connecting different applications or components, facilitating communication and data exchange." },
                { term: "MVC", definition: "Model-View-Controller. An architectural pattern separating applications into three interconnected components for organized and scalable code." },
                
                // N
                { term: "NAT", definition: "Network Address Translation. A technique allowing devices with private IP addresses to communicate with external networks using a gateway." },
                { term: "NoSQL", definition: "A category of databases designed for unstructured or semi-structured data, offering flexibility and scalability alternatives to traditional SQL databases." },
                
                // O
                { term: "OAuth", definition: "An open standard authorization protocol allowing users to authorize third-party applications to access their resources without sharing passwords." },
                { term: "ORM", definition: "Object-Relational Mapping. A programming technique mapping objects in code to rows in relational databases, simplifying data persistence." },
                { term: "OSI Model", definition: "Open Systems Interconnection Model. A conceptual framework defining how network communication occurs across seven abstraction layers." },
                
                // P
                { term: "POS System", definition: "Point of Sale System. The place and equipment where customers execute payment for goods or services, often integrated digital terminals." },
                { term: "Protocol", definition: "A set of rules governing data transmission and communication between devices and systems on a network or the internet." },
                { term: "Proxy", definition: "An intermediary server that forwards client requests to other servers, used for caching, security, and load distribution." },
                { term: "PaaS", definition: "Platform as a Service. A cloud computing model providing a platform for developing, testing, and deploying applications over the internet." },
                
                // Q
                { term: "QoS", definition: "Quality of Service. Networking technologies and protocols ensuring consistent performance, bandwidth, and reliability for network traffic." },
                { term: "Queue", definition: "A data structure following First-In-First-Out (FIFO) principle, widely used in task scheduling and event processing systems." },
                
                // R
                { term: "REST", definition: "Representational State Transfer. An architectural style for designing networked applications using HTTP methods (GET, POST, PUT, DELETE)." },
                { term: "Redis", definition: "An in-memory data store providing fast access to frequently used data, commonly used for caching and real-time analytics." },
                { term: "Repository", definition: "A centralized storage location for code, configuration, and version history, typically managed by version control systems like Git." },
                { term: "RAID", definition: "Redundant Array of Independent Disks. A data storage technology combining multiple drives for improved performance and fault tolerance." },
                
                // S
                { term: "Scalability", definition: "The ability of a system to handle growing workloads by adding resources, growing efficiently with business demands." },
                { term: "SSL Certificate", definition: "Secure Sockets Layer certificate. A digital certificate authenticating website identity and enabling encrypted connections." },
                { term: "SaaS", definition: "Software as a Service. A cloud computing model delivering software applications over the internet via subscription or per-use pricing." },
                { term: "Socket", definition: "An endpoint for network communication within a computer, used for data transmission between processes or over networks." },
                { term: "SSH", definition: "Secure Shell. A protocol providing secure remote access to computers and secure file transfer, using encryption for confidentiality." },
                { term: "SQL", definition: "Structured Query Language. A standardized language used to create, query, and manipulate relational databases." },
                { term: "Sharding", definition: "A database scaling technique horizontally partitioning data across multiple servers based on a shard key." },
                
                // T
                { term: "TCP/IP", definition: "Transmission Control Protocol/Internet Protocol. The fundamental set of protocols enabling reliable, ordered data transmission on the internet." },
                { term: "TLS", definition: "Transport Layer Security. A cryptographic protocol ensuring secure communication over networks, the successor to SSL." },
                { term: "Token", definition: "A piece of data representing authentication credentials or authorization rights, used in modern authentication systems." },
                { term: "Topology", definition: "The physical or logical arrangement of nodes and connections in a network, such as star, mesh, or ring configurations." },
                
                // U
                { term: "UDP", definition: "User Datagram Protocol. A connectionless transport protocol enabling fast data transmission with minimal overhead, prioritizing speed over reliability." },
                { term: "URL", definition: "Uniform Resource Locator. The web address identifying and accessing resources on the internet." },
                
                // V
                { term: "VPN", definition: "Virtual Private Network. A technology creating a safe, encrypted connection over less secure networks like the internet." },
                { term: "Virtualization", definition: "Creating virtual versions of physical resources like servers, storage, or networks to optimize resource utilization and flexibility." },
                { term: "Version Control", definition: "A system tracking changes to files and code over time, enabling collaboration, rollback, and history tracking." },
                
                // W
                { term: "Web3", definition: "The concept of a decentralized internet built on blockchain technology, focusing on user ownership and decentralized applications." },
                { term: "WebSocket", definition: "A protocol providing full-duplex communication channels over a single TCP connection, enabling real-time bidirectional communication." },
                { term: "Webhook", definition: "A mechanism allowing applications to send real-time data to other applications when specific events occur." },
                
                // X
                { term: "XML", definition: "Extensible Markup Language. A text-based format for storing and transporting data that is both human-readable and machine-readable." },
                
                // Y
                { term: "YAML", definition: "YAML Ain't Markup Language. A human-friendly data serialization format commonly used for configuration files and data exchange." },
                
                // Z
                { term: "Zero-Trust Security", definition: "A security model that verifies every user and device regardless of location or network, assuming no implicit trust." }
            ].sort((a, b) => a.term.localeCompare(b.term));

            const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');
            const indexContainer = document.getElementById('alphabetIndex');
            const termsContainer = document.getElementById('glossaryTermsContainer');
            const searchInput = document.getElementById('searchInput');
            const headerOffset = 100;

            const termsByLetter = {};

            // Group terms by first letter
            glossaryData.forEach(item => {
                const firstLetter = item.term.charAt(0).toUpperCase();
                if (!termsByLetter[firstLetter]) {
                    termsByLetter[firstLetter] = [];
                }
                termsByLetter[firstLetter].push(item);
            });

            // Generate alphabet index
            alphabet.forEach(letter => {
                const hasTerms = !!termsByLetter[letter];
                const link = document.createElement('a');
                link.textContent = letter;
                link.href = hasTerms ? `#${letter}` : 'javascript:void(0)';
                link.className = hasTerms ? '' : 'disabled';
                
                if (hasTerms) {
                    link.addEventListener('click', function(e) {
                        e.preventDefault();
                        const target = document.getElementById(letter);
                        if (target) {
                            const targetPosition = target.getBoundingClientRect().top + window.scrollY - headerOffset;
                            window.scrollTo({ top: targetPosition, behavior: 'smooth' });
                            updateActiveIndex(letter);
                        }
                    });
                }
                
                indexContainer.appendChild(link);
            });

            // Generate glossary content
            let contentHTML = '';
            alphabet.forEach(letter => {
                const terms = termsByLetter[letter];
                if (terms && terms.length > 0) {
                    contentHTML += `
                        <div class="term-group fade-in" id="${letter}">
                            <div class="term-group-header">
                                <h2>${letter}</h2>
                            </div>
                            <div class="term-grid">
                    `;
                    
                    terms.forEach(item => {
                        contentHTML += `
                            <div class="term-card">
                                <h3>
                                    
                                    ${item.term}
                                </h3>
                                <p>${item.definition}</p>
                            </div>
                        `;
                    });
                    
                    contentHTML += `
                            </div>
                        </div>
                    `;
                }
            });

            termsContainer.innerHTML = contentHTML;

            // Search functionality
            searchInput.addEventListener('input', function(e) {
                const query = e.target.value.toLowerCase();
                const termCards = document.querySelectorAll('.term-card');
                const termGroups = document.querySelectorAll('.term-group');

                if (query.length === 0) {
                    termCards.forEach(card => card.style.display = '');
                    termGroups.forEach(group => group.style.display = '');
                    return;
                }

                let hasVisibleCards = {};

                termCards.forEach(card => {
                    const term = card.querySelector('h3').textContent.toLowerCase();
                    const definition = card.querySelector('p').textContent.toLowerCase();
                    const matches = term.includes(query) || definition.includes(query);
                    
                    card.style.display = matches ? '' : 'none';
                    
                    if (matches) {
                        const letter = card.closest('.term-group').id;
                        hasVisibleCards[letter] = true;
                    }
                });

                termGroups.forEach(group => {
                    group.style.display = hasVisibleCards[group.id] ? '' : 'none';
                });
            });

            // Scroll spy
            const termGroups = document.querySelectorAll('.term-group');

            function updateActiveIndex(activeLetter) {
                document.querySelectorAll('.alphabet-nav a').forEach(a => {
                    a.classList.remove('active-letter');
                });
                const activeLink = document.querySelector(`.alphabet-nav a[href="#${activeLetter}"]`);
                if (activeLink) {
                    activeLink.classList.add('active-letter');
                }
            }

            function handleScroll() {
                let currentLetter = '';
                
                for (let i = 0; i < termGroups.length; i++) {
                    if (termGroups[i].getBoundingClientRect().top <= headerOffset) {
                        currentLetter = termGroups[i].id;
                    } else {
                        break;
                    }
                }
                
                if (currentLetter) {
                    updateActiveIndex(currentLetter);
                }
            }

            window.addEventListener('scroll', handleScroll);
            handleScroll();
        });